"""Added returned date and in stock

Revision ID: cea85e843118
Revises: 5d0774b26ea0
Create Date: 2024-03-23 19:11:38.186456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea85e843118'
down_revision = '5d0774b26ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('returned_date', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('in_stock')

    with op.batch_alter_table('book_requests', schema=None) as batch_op:
        batch_op.drop_column('returned_date')

    # ### end Alembic commands ###
